[build]
  # Directory with the package.json and build scripts
  base = "client"

  # Build command
  command = "npm run build"

  # Directory to publish (relative to base)
  publish = "dist"

# Environment variables for the build
[build.environment]
  NODE_VERSION = "20"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
